name: Test Client Build with docker

on:
  push:
    paths:
      - client/**
      - client/clientbuildtest.Dockerfile
      - .github/workflows/test-client-build-docker.yml
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - client/**
      - client/clientbuildtest.Dockerfile
      - .github/workflows/test-client-build-docker.yml
  workflow_dispatch:      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Client
      run: | 
         cd client
         DOCKER_BUILDKIT=1 docker build . --file clientbuildtest.Dockerfile --output build --tag client:$(date +%s)
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: out.tar
